// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greet.proto

/*
Package greet is a generated protocol buffer package.

It is generated from these files:
	greet.proto

It has these top-level messages:
	HelloRequest
	HelloResponse
	GreetError
*/
package greet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type HelloResponse struct {
	Greeting string        `protobuf:"bytes,1,opt,name=greeting" json:"greeting,omitempty"`
	Success  bool          `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
	Errors   []*GreetError `protobuf:"bytes,3,rep,name=errors" json:"errors,omitempty"`
}

func (m *HelloResponse) Reset()                    { *m = HelloResponse{} }
func (m *HelloResponse) String() string            { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()               {}
func (*HelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func (m *HelloResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *HelloResponse) GetErrors() []*GreetError {
	if m != nil {
		return m.Errors
	}
	return nil
}

type GreetError struct {
	Code   string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Entity string `protobuf:"bytes,2,opt,name=entity" json:"entity,omitempty"`
}

func (m *GreetError) Reset()                    { *m = GreetError{} }
func (m *GreetError) String() string            { return proto.CompactTextString(m) }
func (*GreetError) ProtoMessage()               {}
func (*GreetError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GreetError) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *GreetError) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "HelloResponse")
	proto.RegisterType((*GreetError)(nil), "GreetError")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GreetingService service

type GreetingServiceClient interface {
	Greeting(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type greetingServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreetingServiceClient(cc *grpc.ClientConn) GreetingServiceClient {
	return &greetingServiceClient{cc}
}

func (c *greetingServiceClient) Greeting(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := grpc.Invoke(ctx, "/GreetingService/greeting", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GreetingService service

type GreetingServiceServer interface {
	Greeting(context.Context, *HelloRequest) (*HelloResponse, error)
}

func RegisterGreetingServiceServer(s *grpc.Server, srv GreetingServiceServer) {
	s.RegisterService(&_GreetingService_serviceDesc, srv)
}

func _GreetingService_Greeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetingServiceServer).Greeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GreetingService/Greeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetingServiceServer).Greeting(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GreetingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GreetingService",
	HandlerType: (*GreetingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "greeting",
			Handler:    _GreetingService_Greeting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greet.proto",
}

func init() { proto.RegisterFile("greet.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x14, 0x84, 0x15, 0x8a, 0x42, 0xfb, 0x42, 0x01, 0xbd, 0x01, 0x59, 0x9d, 0xa2, 0xb0, 0x98, 0xc5,
	0x43, 0x59, 0x18, 0x98, 0x90, 0x50, 0x99, 0xcd, 0x2f, 0x28, 0xe6, 0xc9, 0x0a, 0x4a, 0x62, 0xe3,
	0xe7, 0x20, 0xf8, 0xf7, 0x28, 0x96, 0x43, 0x60, 0xf3, 0x77, 0x3e, 0x9f, 0xee, 0x0c, 0x95, 0x0d,
	0x44, 0x51, 0xf9, 0xe0, 0xa2, 0x6b, 0x24, 0x9c, 0x3f, 0x53, 0xd7, 0x39, 0x4d, 0x1f, 0x23, 0x71,
	0x44, 0x01, 0x67, 0x3d, 0x31, 0x1f, 0x2d, 0x89, 0xa2, 0x2e, 0xe4, 0x46, 0xcf, 0xd8, 0xbc, 0xc3,
	0x36, 0x3b, 0xd9, 0xbb, 0x81, 0x09, 0x77, 0xb0, 0x4e, 0x49, 0xed, 0x60, 0xb3, 0xf7, 0x97, 0xa7,
	0x18, 0x1e, 0x8d, 0x21, 0x66, 0x71, 0x52, 0x17, 0x72, 0xad, 0x67, 0xc4, 0x1b, 0x28, 0x29, 0x04,
	0x17, 0x58, 0xac, 0xea, 0x95, 0xac, 0xf6, 0x95, 0x3a, 0x4c, 0x8f, 0x9e, 0x26, 0x4d, 0xe7, 0xab,
	0xe6, 0x1e, 0x60, 0x51, 0x11, 0xe1, 0xd4, 0xb8, 0xb7, 0xb9, 0x50, 0x3a, 0xe3, 0x35, 0x94, 0x34,
	0xc4, 0x36, 0x7e, 0xa7, 0xfc, 0x8d, 0xce, 0xb4, 0x7f, 0x80, 0xcb, 0x43, 0x2e, 0xf1, 0x42, 0xe1,
	0xb3, 0x35, 0x84, 0xb7, 0x4b, 0x4f, 0xdc, 0xaa, 0xbf, 0x6b, 0x77, 0x17, 0xea, 0xdf, 0xa4, 0x47,
	0x84, 0x2b, 0xe3, 0x7a, 0x45, 0x5f, 0xc7, 0xde, 0x77, 0xa4, 0x6c, 0xf0, 0xe6, 0xb5, 0x4c, 0x1f,
	0x75, 0xf7, 0x13, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x69, 0x1f, 0x90, 0x37, 0x01, 0x00, 0x00,
}
